server {
    listen 443 ssl;
    server_name localhost;

    ssl_certificate     /etc/ssl/lab4/server.crt;
    ssl_certificate_key /etc/ssl/lab4/server.key;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;
    ssl_ciphers "ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-GCM-SHA256";

    location / {
        return 200 "Lab4 TLS OK\n";
        add_header Content-Type text/plain;
    }
}

server {
    listen 80;
    server_name localhost;
    return 301 https://$host$request_uri;
}
